spring:
  application:
    name: commerce-api
  cloud:
    config:
      enabled: false
      import-check:
        enabled: false
  profiles:
    default: local
    group:
      local-config:
        - local
        - config
      dev-config:
        - dev
        - config

toy-commerce:
  config:
    source: local
    message: 로컬 기본 설정입니다.
  settlement:
    legacy:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
