spring:
  cache:
    type: redis
    redis:
      cache-null-values: false
      key-prefix: "toy-commerce:"
      time-to-live: 10m
      use-key-prefix: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 2s
