spring:
  application:
    name: commerce-api
  cloud:
    config:
      enabled: false
      import-check:
        enabled: false
  profiles:
    default: local
    group:
      local-mysql:
        - local
        - mysql
      local-mysql-redis:
        - local
        - mysql
        - redis
      local-mysql-kafka:
        - local
        - mysql
        - kafka
      local-mysql-redis-kafka:
        - local
        - mysql
        - redis
        - kafka
      local-mongo:
        - local
        - mongo
      local-mysql-redis-kafka-mongo:
        - local
        - mysql
        - redis
        - kafka
        - mongo
      local-config:
        - local
        - config
      local-mysql-config:
        - local
        - mysql
        - config
      local-mysql-redis-kafka-config:
        - local
        - mysql
        - redis
        - kafka
        - config
      local-mysql-redis-kafka-mongo-config:
        - local
        - mysql
        - redis
        - kafka
        - mongo
        - config

toy-commerce:
  config:
    source: local
    message: 로컬 기본 설정입니다.

management:
  endpoints:
    web:
      exposure:
        include: health,info
