input {
  syslog {
    port => 5514
    type => "commerce-api"
  }
}

filter {
  if [type] == "commerce-api" {
    mutate {
      add_field => {
        "service.name" => "commerce-api"
        "service.environment" => "dev"
      }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "toy-commerce-logs-%{+YYYY.MM.dd}"
  }

  stdout {
    codec => rubydebug
  }
}
